### ISSUE TITLE
아이폰 카카오 로그인 문제

### ISSUE THREAD

**Issue by TAE-COLA** [1stLunchVote/1stLunchVote_Flutter_Release#28]
## 이슈 요약
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/69046742/235998393-cbb67280-daed-401e-9b36-d4b35eefd21c.png">

## 세부 내용
아이폰으로 카카오 로그인 버튼 클릭시 다음과 같은 오류가 발생!

**Comment by activedg** [comment]
@TAE-COLA 카카오 로그인 이제 없습니다!
